### ISSUE TITLE
exact code but failed to get redirect response TypeError: fetch failed

### ISSUE THREAD

**Issue by jfmoura** [WebDevSimplified/next-13-todo-list#4]
I cloned your project and then updated the libraries to the latest version and I just noticed that your code is presenting this error.
It still works despite the bug, but the Todos on the main page are no longer updated.

I just discovered that this error occurs with next.js v13.4.12, if next.js v13.4.1 version is applied it works perfectly.
I guess there must be a bug.
I hope you find this post helpful.

```js
async function createTodo(data: FormData) {
  "use server";
  const title = data.get("title")?.valueOf();
  if (typeof title !== "string" || title.length === 0) {
    throw new Error("Invalid title");
  }

  await prisma.todo.create({ data: { title: title, complete: false } });
  redirect("/");  // <-- The error occurs when adding this line.
}
```
everything works perfectly until I place the redirect("/"); It shows me the following error:
```
prisma:query SELECT 1
prisma:query BEGIN
prisma:query INSERT INTO `main`.`Todo` (`id`, `title`, `complete`, `cleatedAt`, `updatedAt`) VALUES (?,?,?,?,?) RETURNING `id` AS `id`
prisma:query SELECT `main`.`Todo`.`id`, `main`.`Todo`.`title`, `main`.`Todo`.`complete`, `main`.`Todo`.`cleatedAt`, `main`.`Todo`.`updatedAt` FROM `main`.`Todo` WHERE `main`.`Todo`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
failed to get redirect response TypeError: fetch failed
    at Object.fetch (/home/jorge/next-13-todo-list/node_modules/next/dist/compiled/undici/index.js:1:26669) {
  cause: RequestContentLengthMismatchError: Request body length does not match content-length header
      at write (/home/jorge/next-13-todo-list/node_modules/next/dist/compiled/undici/index.js:1:67105)
      at _resume (/home/jorge/next-13-todo-list/node_modules/next/dist/compiled/undici/index.js:1:66726)
      at resume (/home/jorge/next-13-todo-list/node_modules/next/dist/compiled/undici/index.js:1:65413)
      at connect (/home/jorge/next-13-todo-list/node_modules/next/dist/compiled/undici/index.js:1:65301) {
    code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
  }
}
```

**Comment by Trewaters** [comment]
There is an error but the ToDo list does refresh if I do it manually. 

I suggest adding this to the next.config.js. It worked for me. I still get the error but my list shows the most recent todo item.

```
headers: () => [
        {
          source: '/(.*)',
          headers: [
            {
              key: 'Cache-Control',
              value: 'no-store',
            },
          ],
        },
      ],
```

Good luck!

**Comment by jfmoura** [comment]
> There is an error but the ToDo list does refresh if I do it manually.
> 
> I suggest adding this to the next.config.js. It worked for me. I still get the error but my list shows the most recent todo item.
> 
> ```
> headers: () => [
>         {
>           source: '/(.*)',
>           headers: [
>             {
>               key: 'Cache-Control',
>               value: 'no-store',
>             },
>           ],
>         },
>       ],
> ```
> 
> Good luck!

Thank you for the recommendation👍, but it hasn't had any effect😓.

**Comment by satvik-2-9** [comment]
I have the same error, the problem being highlighted on the same line :

 `redirect("/");`

The browser shows : 
`
Unhandled Runtime Error
Error: Invalid redirect arguments. Please use a single argument URL, e.g. res.redirect('/destination') or use a status code and URL, e.g. res.redirect(307, '/destination').
`
Adding an argument in the redirect does not solve the problem too. Kindly help.

UPD:

The error is gone but as @Trewaters suggested, the new item only comes after manually refreshing. Tried adding the headers too, @Trewaters that did not work.
